# Get editor completions based on the config schema

"$schema" = 'https://starship.rs/config-schema.json'

format="""$character$directory$git_branch$git_status$character"""

add_newline = false

[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
format = "[git:\\($branch\\)]($style) "
disabled = false 
style = 'bold red'

[git_status]
modified = 'M'
ahead = 'A'
staged = 'S'
conflicted = 'C'
deleted = 'D'
behind = 'B'
untracked = 'U'
